### ISSUE TITLE
Change Crate Name

### ISSUE THREAD

**Issue by logannc** [logannc/fuzzywuzzy-rs#10]
I am so far unable to contact the owner of the crate on crates.io. The staff of crates.io has suggested I pick a different name if I'm unable to reach them.

If I don't hear back from @JacksonGariety in the next week, I'll change the name here to fuzzywuzzy and publish under that.

**Comment by seanpianka** [comment]
I would definitely agree with taking "fuzzywuzzy" if it's still available. I see [fuzzy-wuzzy](https://github.com/carols10cents/fuzzy-wuzzy) from Google, but it seems unrelated/not on crates.io. Having the original name would probably help discoverability as well.

What're your thoughts on "fuzzywuzzy" versus "fuzzywuzzy-rs" for the repository name?

**Comment by logannc** [comment]
probably the latter so that if someone is contributing to fuzzywuzzy and this repo they dont get collisions :)

**Comment by logannc** [comment]
Crate and repo name have been changed. I have omitted creating a replacement repo for logannc/fuzzyrusty as github redirects to this repo.

**Comment by seanpianka** [comment]
I have created [a pull request in fuzzywuzzy](https://github.com/seatgeek/fuzzywuzzy/pull/281) for updating the name of the port in their README.
