### ISSUE TITLE
Update repository description and topics

### ISSUE THREAD

**Issue by seanpianka** [logannc/fuzzywuzzy-rs#17]
The original's description is:

> Fuzzy String Matching in Python

What are your thoughts on changing ours' to the following:

> Fuzzy String Matching in Rust, a port of the Python package [fuzzywuzzy](https://github.com/seatgeek/fuzzywuzzy).

For topics, here's a list of ones off the top of my head. These could be updated in the `Cargo.toml` for crates.io, as well:
* string
* text
* processing
* utility
* matching
* fuzzy
* wuzzy
* extract
* deduplicate
* duplicates
* text-processing

**Comment by logannc** [comment]
Sure, though we're limited to 5 keywords on crates.io

**Comment by seanpianka** [comment]
I'm not able to update the description of the repository, it seems only the owner can do that. However, I've updated the keywords in #18.

**Comment by logannc** [comment]
I can't either. It's purely based on the latest published crate version, I think.

**Comment by logannc** [comment]
I think this issue can be closed as it will be 'resolved' when we next release.
