### ISSUE TITLE
The name of this library might need a rethink

### ISSUE THREAD

**Issue by nomad-software** [logannc/fuzzywuzzy-rs#27]
> The phrase has been used as a derogatory term to describe a black person. [2] The term "Fuzzy Wuzzy Angels" was used by Australian soldiers during World War II to describe Papua New Guinean stretcher bearers. The term was not widely deemed to be problematic when it was used by Rudyard Kipling and British soldiers during the Sudan Campaign or by Australian soldiers in the 20th century, however many contemporary commentators deem it to be a racist slur. [3]

https://en.wikipedia.org/wiki/Fuzzy-Wuzzy
https://www.dictionary.com/browse/fuzzy-wuzzy

**Comment by logannc** [comment]
1. The name comes from the popular python string fuzzy matching library on which this is based.
2. Fuzzy wuzzy was a bear
3. While I am sympathetic to the quest for inclusive terminology, I do not believe this name causes anyone offensive or cause for exclusion within acceptable margins.

**Comment by nomad-software** [comment]
Unfortunately a fuzzy wuzzy is not a bear.

https://bradmckenna.wordpress.com/2020/06/24/fuzzy-wuzzy/

There are a load more explanations here too.

https://www.phrases.org.uk/meanings/fuzzy-wuzzy.html
https://abcnews.go.com/Politics/commonly-terms-racist-origins/story?id=71840410
https://aninjusticemag.com/7-racist-slurs-which-you-should-drop-from-your-vocabulary-885c56ba97ae
https://www.dictionary.com/e/s/offensive-words-hiding-plain-sight/#fuzzy-wuzzy

**Comment by logannc** [comment]
I am not going to engage in your drive-by politicking, nor do I appreciate trivializing the real harms that can be caused by non-inclusive terminology by insinuating *this* is somehow on the same level of concern as terms that actually cause real harm  (assuming I even accept that fuzzy wuzzy cannot possibly refer to anything but a dated, unknown derogatory term).

Go stir up trouble somewhere else.

**Comment by logannc** [comment]
I apologize if you're raising this in good faith. But when someone pops up with no comments other than something only vaguely related to racial politics, I assume they just want to pat themselves on the back or that it's otherwise in bad faith.

**Comment by nomad-software** [comment]
How is it bad faith? It's literally a racial slur against black people. Maybe not one you're familiar with but in the UK it's very well known. It's origins go back to the colonial wars in Africa.

I hate nonsense political correctness as much as anyone but honestly this name is really offensive in the UK. You don't often hear it because it's an old word that was popular with baby-boomers back in the 60's and 70's, it even used to feature on TV[1] but it's still a problem word, even today.

The company where I work were thinking of using the original Python library but I was pretty uncomfortable with its name (imagine seeing that in build pipelines) and we decided to use something else and to be honest, I couldn't be bothered to raise an issue over there. To see it perpetuated here, in another language is unreal.

Leave it as you wish (at least I've brought it to your attention) but don't think it's not a problematic word, especially for people in the UK.

[1] https://metro.co.uk/2021/01/04/bbc-issues-warning-for-using-discriminatory-language-in-dads-army-film-13844036/
