### ISSUE TITLE
fuzzyrusty

### ISSUE THREAD

**Issue by sgrust01** [logannc/fuzzywuzzy-rs#3]
Hey Logan - I was looking for a port for fuzzywuzzy, and after some google landed here. Any thoughts on the future of this crate?

Cheers,
SG

**Comment by logannc** [comment]
It'd kind of slipped my mind, to be honest. I'd have to refamiliarize myself with the inspiring python package, but I think I covered the most important bits, leaving a few things not quite done.

I wouldn't mind picking it back up again.

Did you have anything in mind?

**Comment by sgrust01** [comment]
@logannc Thanks for circling back on this. Also, hope you and your family are all keeping well. 

Couple of years back I was looking for a package for handling typos (in names specially), found fuzzywuzzy,  and it just worked then. Recently, i was working with [tantivy](https://github.com/tantivy-search/tantivy) for my crate [json-surf](https://github.com/sgrust01/json-surf), and was hoping to provide buffer for typo in names to retrieve data accurately. e.g jonh should mean john

Cheers,
SG

**Comment by logannc** [comment]
Sure, that all makes sense. I've built a similar such thing using fuzzywuzzy which is what inspired me to port it. But are you asking if I'll build a corrector or add some feature to fuzzyrusty? What is the actionable item you're asking about? If you want a typo corrector, that can be done but it should probably be a crate that just depends on something like fuzzyrusty. If you're asking for a feature addition to fuzzyrusty ,I'm missing what it is.

**Comment by sgrust01** [comment]
@logannc - I was referring to process module

```python
>>> from fuzzywuzzy import process
>>> choices = ["Atlanta Falcons", "New York Jets", "New York Giants", "Dallas Cowboys"]
>>> process.extract("new york jets", choices, limit=2)
[('New York Jets', 100), ('New York Giants', 79)]
>>> process.extract("new yorkjets", choices, limit=2)
[('New York Jets', 96), ('New York Giants', 74)]
>>> process.extract("new yrok jets", choices, limit=2)
[('New York Jets', 92), ('New York Giants', 71)]
>>> 
```
In last example: process extraction has an in-build tolerance towards typos

Cheers,
SG.

**Comment by sgrust01** [comment]
@logannc Hi Logon - Hope you are keeping well. Found a crate [symspell](https://github.com/reneklacan/symspell), and was able to make typo correction work([here](https://github.com/sgrust01/json-surf/blob/master/examples/06_fuzzy_user_name.rs)). Closing this issue, but will be happy to work with you.
Cheers,
SG.

**Comment by seanpianka** [comment]
@sgrust01 This crate has been updated with a subset of the original process methods. Let me know your thoughts! 

We're still missing other process methods, I've only added the ones I need :)
