### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by seanpianka** [logannc/fuzzywuzzy-rs#8]
How about MIT?

**Comment by logannc** [comment]
As based on or influenced by fuzzywuzzy to various degrees, I will probably mirror their license which is GPL2, which is probably the most compliant option anyway. IANAL so I don't know to what degree I am obligated by fuzzywuzzy's GPL2, but it's a fine license. If fuzzywuzzy makes their's more permissive, we can follow suit.
